language: python
python:
  - '2.7'
install: pip install tox
env:
  - TOXENV=py27
matrix:
  fast_finish: true
  include:
    - env: TOXENV=lint
      python: '2.7'
    - env: TOXENV=py27
      python: '2.7'
script:
  - tox -e $TOXENV
cache: pip
